# Generated by Django 5.2.7 on 2025-10-16 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade_medida', models.CharField(choices=[('UN', 'Unidade'), ('PC', 'Peça'), ('KG', 'Quilograma'), ('MT', 'Metro'), ('LT', 'Litro'), ('CX', 'Caixa'), ('PCT', 'Pacote')], default='UN', max_length=3)),
                ('estoque_minimo', models.IntegerField(default=0)),
                ('estoque_atual', models.IntegerField(default=0)),
                ('localizacao', models.CharField(blank=True, help_text='Localização no depósito', max_length=100, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produto.categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
    ]
