# Generated by Django 5.2.7 on 2025-10-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_produto_preco_custo_alter_produto_preco_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='status_ativo',
            field=models.BooleanField(default=True),
        ),
    ]
