# Generated by Django 5.2.7 on 2025-10-16 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Escola')),
                ('codigo_inep', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código INEP')),
                ('tipo_escola', models.CharField(choices=[('municipal', 'Municipal'), ('estadual', 'Estadual'), ('federal', 'Federal'), ('particular', 'Particular')], default='municipal', max_length=20)),
                ('nivel_ensino', models.CharField(choices=[('infantil', 'Educação Infantil'), ('fundamental', 'Ensino Fundamental'), ('medio', 'Ensino Médio'), ('tecnico', 'Ensino Técnico'), ('superior', 'Ensino Superior')], default='fundamental', max_length=20)),
                ('endereco', models.TextField(verbose_name='Endereço Completo')),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(default='São Paulo', max_length=100)),
                ('estado', models.CharField(default='SP', max_length=2)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('diretor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Diretor')),
                ('responsavel_contato', models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsável para Contato')),
                ('telefone_responsavel', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do Responsável')),
                ('quantidade_alunos', models.IntegerField(default=0, verbose_name='Quantidade de Alunos')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Escola',
                'verbose_name_plural': 'Escolas',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome'], name='escola_esco_nome_54639f_idx'), models.Index(fields=['cidade'], name='escola_esco_cidade_8a15a9_idx'), models.Index(fields=['ativo'], name='escola_esco_ativo_68ce5f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContatoEscola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('telefone', 'Telefone'), ('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('outro', 'Outro')], max_length=20)),
                ('valor', models.CharField(max_length=100)),
                ('observacao', models.CharField(blank=True, max_length=100, null=True)),
                ('principal', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='escola.escola')),
            ],
            options={
                'verbose_name': 'Contato da Escola',
                'verbose_name_plural': 'Contatos das Escolas',
                'ordering': ['-principal', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoEscola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('cadastro', 'Cadastro'), ('atualizacao', 'Atualização'), ('visita', 'Visita'), ('entrega', 'Entrega'), ('observacao', 'Observação'), ('outro', 'Outro')], max_length=20)),
                ('descricao', models.TextField()),
                ('data_evento', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='escola.escola')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico da Escola',
                'verbose_name_plural': 'Históricos das Escolas',
                'ordering': ['-data_evento'],
            },
        ),
    ]
