# Generated by Django 5.2.7 on 2025-10-16 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrega', '0001_initial'),
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='escola.escola'),
        ),
        migrations.DeleteModel(
            name='Escola',
        ),
    ]
